import streamlit as st
import pandas as pd
import joblib
import numpy as np
import plotly.graph_objects as go
import time
from fpdf import FPDF
import base64

# --- 1. SYSTEM CONFIGURATION ---
st.set_page_config(
    page_title="TITAN-AI | Body Analytics",
    page_icon="⚡",
    layout="wide"
)

# Custom CSS for High-Tech / Neon Aesthetics
st.markdown("""
    <style>
    .main { background-color: #020617; color: #00f2ff; font-family: 'Segoe UI', sans-serif; }
    .tech-header {
        font-size: 4rem !important;
        font-weight: 900;
        background: linear-gradient(90deg, #00f2ff, #0062ff);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        letter-spacing: 5px;
        text-align: center;
        text-shadow: 0 0 30px rgba(0, 242, 255, 0.3);
        margin-bottom: 20px;
    }
    div[data-testid="stMetricValue"] { font-size: 75px !important; color: #00f2ff !important; }
    .stButton > button {
        width: 100% !important; height: 3.5em !important; font-size: 1.3rem !important;
        background: linear-gradient(45deg, #00f2ff, #0062ff) !important;
        border: none !important; color: white !important; font-weight: bold !important;
        box-shadow: 0 0 15px rgba(0, 242, 255, 0.4) !important;
    }
    .stExpander { background-color: #0f172a !important; border: 1px solid #1e293b !important; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. PDF REPORT GENERATOR FUNCTION ---
def create_pdf(name, age, gender, p_class, p_jump, recs):
    # Using fpdf2 for better encoding handling
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font('helvetica', 'B', 20)
    pdf.set_text_color(0, 100, 255)
    pdf.cell(0, 15, 'TITAN-AI: PERFORMANCE REPORT', ln=True, align='C')
    pdf.line(10, 30, 200, 30)
    pdf.ln(10)
    
    # Subject Info
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Subject Name: {name}", ln=True)
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 8, f"Age: {age} | Gender: {gender}", ln=True)
    pdf.ln(5)
    
    # Results Section
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, " ANALYTICAL RESULTS", ln=True, fill=True)
    pdf.set_font('helvetica', '', 12)
    pdf.cell(0, 10, f"Predicted Performance Grade: Rank {p_class}", ln=True)
    pdf.cell(0, 10, f"Predicted Broad Jump Distance: {p_jump:.2f} cm", ln=True)
    pdf.ln(10)
    
    # Recommendations
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, "System Recommendations:", ln=True)
    pdf.set_font('helvetica', 'I', 11)
    pdf.multi_cell(0, 8, recs)
    
    pdf.set_y(-25)
    pdf.set_font('helvetica', 'I', 8)
    pdf.cell(0, 10, "Generated by TITAN-AI Body Performance Analytics System - 2026", align='C')
    
    return pdf.output()

# --- 3. MODEL LOADING ---
@st.cache_resource
def load_assets():
    # Ensure these files exist in your directory
    clf = joblib.load('classifier_model.pkl')
    reg = joblib.load('regression_model.pkl')
    scaler = joblib.load('scaler.pkl')
    return clf, reg, scaler

try:
    clf, reg, scaler = load_assets()
except Exception as e:
    st.error(f"Error loading models: {e}. Ensure .pkl files are in the same folder.")

# --- 4. MAIN INTERFACE ---
st.markdown("<h1 class='tech-header'>TITAN PERFORMANCE AI</h1>", unsafe_allow_html=True)

# Sidebar
with st.sidebar:
    st.markdown("<h2 style='color:#00f2ff;'>📡 COMMAND CENTER</h2>", unsafe_allow_html=True)
    st.image("https://cdn-icons-png.flaticon.com/512/2097/2097276.png", width=120)
    st.divider()
    st.subheader("👥 PROJECT TEAM")
    team = ["A. Zoghli", "E. TagElsir", "O. Mohamed", "M. Hassan", "A. Ibrahim"]
    for member in team:
        st.code(f"MEMBER: {member.upper()}")
    st.divider()
    st.info("System Status: Operational")

# Input/Output Columns
col_in, col_out = st.columns([1, 1.2])

with col_in:
    st.markdown("### 🧬 BIOMETRIC SCANNER")
    user_name = st.text_input("ATHLETE NAME", "Enter name...")
    age = st.slider("AGE INDEX", 10, 80, 25)
    gender_input = st.selectbox("BIOLOGICAL GENDER", ["Male", "Female"])
    height = st.number_input("HEIGHT (CM)", 120.0, 220.0, 175.0)
    weight = st.number_input("WEIGHT (KG)", 30.0, 150.0, 75.0)
    fat = st.slider("BODY FAT %", 5.0, 50.0, 18.0)
    
    with st.expander("⚡ ADVANCED PERFORMANCE DATA"):
        grip = st.number_input("GRIP STRENGTH (kg)", 0.0, 100.0, 45.0)
        flex = st.number_input("FLEXIBILITY (BEND cm)", -20.0, 40.0, 15.0)
        situps = st.number_input("CORE (SIT-UPS counts)", 0, 100, 45)
        sys = st.number_input("SYSTOLIC BP", 80, 200, 120)
        dias = st.number_input("DIASTOLIC BP", 40, 130, 80)

    analyze = st.button("EXECUTE ANALYSIS SCAN")

# --- 5. LOGIC AND PREDICTION ---
if analyze:
    with st.spinner("INITIATING NEURAL INFERENCE..."):
        time.sleep(1)
        # Process gender for model (0 for Male, 1 for Female as per project docs)
        gender_val = 0 if gender_input == "Male" else 1
        
        # Prepare Feature Vector
        features = [age, gender_val, height, weight, fat, dias, sys, grip, flex, situps]
        input_df = pd.DataFrame([features], columns=[
            'age', 'gender', 'height_cm', 'weight_kg', 'body_fat_pct', 
            'diastolic', 'systolic', 'gripForce', 'sit_bend_forward_cm', 'sit_ups_counts'
        ])
        
        # Predict
        scaled_data = scaler.transform(input_df)
        p_class = clf.predict(scaled_data)[0]
        p_jump = reg.predict(scaled_data)[0]

        with col_out:
            st.markdown("### 🛰️ ANALYTICAL OUTPUT")
            res1, res2 = st.columns(2)
            res1.metric("GRADE RANK", f"CLASS {p_class}")
            res2.metric("JUMP POWER", f"{p_jump:.1f} CM")
            
            # Recommendation Logic
            rec_text = f"The athlete is classified as Grade {p_class}. Focus on flexibility and core endurance is suggested to improve explosive power index."
            st.info(f"💡 RECOMMENDATION: {rec_text}")
            
            # PDF Download Button
            try:
                pdf_data = create_pdf(user_name, age, gender_input, p_class, p_jump, rec_text)
                st.download_button(
                    label="📥 DOWNLOAD PDF REPORT",
                    data=bytes(pdf_data),
                    file_name=f"Performance_Report_{user_name}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF Generation Error: {e}")
            
            # Gauge Chart Visualization
            fig = go.Figure(go.Indicator(
                mode = "gauge+number",
                value = p_jump,
                title = {'text': "Explosive Power (Jump Distance)"},
                gauge = {
                    'axis': {'range': [None, 300], 'tickwidth': 1, 'tickcolor': "#00f2ff"},
                    'bar': {'color': "#00f2ff"},
                    'bgcolor': "#0f172a",
                    'steps': [
                        {'range': [0, 150], 'color': '#1e293b'},
                        {'range': [150, 250], 'color': '#334155'}
                    ],
                }
            ))
            fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", font_color="#00f2ff", height=350)
            st.plotly_chart(fig, use_container_width=True)

st.markdown("<p style='text-align: center; color: #334155; margin-top: 50px;'>// TITAN CORE V5.0 // ENGLISH EDITION // 2026</p>", unsafe_allow_html=True)
